version: '3.4'

services:
    microservicewebapi:
        container_name: microservicewebapi
        image: microservicewebapi
        build:
            context: .
            dockerfile: MicroService.WebApi/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        ports:
            - 12000:80
        depends_on:
            - seq

    seq:
        container_name: seq
        image: datalust/seq:latest
        ports:
            - 5341:80
        environment:
            - ACCEPT_EULA=Y
        restart: unless-stopped